Repository the-collab-lab/tcl-77-smart-shopping-list, pull requests merged in 2024-09, with the labels that each got.

#29 Issue 7: Adding list filtering
  package-lock.json
  package.json
  src/App.tsx
  src/components/FilterListInput.tsx
  src/views/List.tsx
Labels: enhancement, new feature

#27 Restrict Navigation Bar Links Based on User Authentication Status
  src/App.tsx
  src/api/index.ts
  src/api/useAuth.tsx
  src/components/AuthenticatedNavBar.css
  src/components/AuthenticatedNavBar.tsx
  src/components/ProtectedRoute.tsx
  src/components/forms/ShareListForm.tsx
  src/components/index.ts
  src/index.tsx
  src/views/Layout.css
  src/views/Layout.tsx
  src/views/ManageList.tsx
  src/views/PageNotFound.tsx
  src/views/index.ts
Labels: bug fix, enhancement, refactoring

#31 Mark item as purchased & update DB
  src/App.tsx
  src/api/README.md
  src/api/firebase.ts
  src/components/ListItem.tsx
  src/utils/dates.ts
  src/views/authenticated/List.tsx
Labels: enhancement, new feature

#33 Updating dateNextPurchased with smart calculation of new date
  package-lock.json
  package.json
  src/api/firebase.ts
  src/utils/dates.ts
Labels: enhancement, new feature

#34 Issue # 10 Prevent user from adding duplicate or empty item to the list
  src/App.tsx
  src/components/forms/AddItemForm.tsx
  src/utils/validateTrimmedString.ts
  src/views/authenticated/ManageList.tsx
Labels: enhancement

#36 Issue # 12: Deleting a shopping list item
  src/api/firebase.ts
  src/components/ListItem.tsx
Labels: enhancement, new feature

#35 Issue #13: Sort item list by when to buy urgency
  src/api/README.md
  src/api/firebase.ts
  src/components/ListItem.css
  src/components/ListItem.tsx
  src/views/authenticated/List.tsx
Labels: enhancement, new feature

#40 Updated `api` readme with `deleteItem` parameter info
  src/api/README.md
Labels: documentation

#41 A way for an new user to understand how the app functions
  index.html
  src/App.tsx
  src/api/useAuth.tsx
  src/components/CreateList.tsx
  src/components/NavBar.css
  src/components/authenticated/AuthenticatedNavBar.tsx
  src/components/index.ts
  src/components/unauthenticated/UnauthenticatedNavBar.tsx
  src/icons/GithubLogo.svg
  src/icons/LinkedInLogo.svg
  src/views/Home.tsx
  src/views/Layout.tsx
  src/views/authenticated/AuthenticatedHome.tsx
  src/views/index.ts
  src/views/unauthenticated/About.tsx
  src/views/unauthenticated/UnauthenticatedHome.tsx
  vite.config.js
Labels: enhancement, new feature
