Repository the-collab-lab/tcl-77-smart-shopping-list, pull requests merged in 2024-10, with the labels that each got.

#46 Feat/add item quantity
  src/api/firebase.ts
  src/components/ListItem.tsx
  src/components/forms/AddItemForm.tsx
  src/components/forms/ItemQuantityForm.tsx
Labels: enhancement, new feature

#59 Fix Prod Build Bug w/ Bootstrap & Updated Dependencies
  index.html
  package-lock.json
  package.json
  src/components/NavBar.css
  src/components/NavBar.scss
  src/components/authenticated/AuthenticatedNavBar.tsx
  src/components/unauthenticated/UnauthenticatedNavBar.tsx
  src/index.scss
  src/index.tsx
  vite.config.js
Labels: bug fix, update dependencies

#62 Quantity Bug Fix on Add Items View!
  src/components/forms/AddItemForm.tsx
Labels: bug fix

#65 Issue#55: Style Home Page
  src/components/CreateList.tsx
  src/components/SingleList.scss
  src/styles/_mixins.scss
  src/styles/_variables.scss
  src/views/Home.scss
  src/views/Home.tsx
  src/views/Layout.scss
  src/views/authenticated/AuthenticatedHome.scss
  src/views/authenticated/AuthenticatedHome.tsx
  src/views/unauthenticated/UnauthenticatedHome.scss
  src/views/unauthenticated/UnauthenticatedHome.tsx
Labels: design

#64 Header Design & Carousel Base + About page
  src/api/useAuth.tsx
  src/assets/icons/GithubLogo.svg
  src/assets/icons/LinkedInLogo.svg
  src/assets/images/sample.png
  src/components/AuthenticatedNavBar.tsx
  src/components/CreateList.tsx
  src/components/FilterListInput.tsx
  src/components/ListItem.tsx
  src/components/NavBar.scss
  src/components/SingleList.tsx
  src/components/authenticated/AuthenticatedNavBar.tsx
  src/components/forms/AddItemForm.tsx
  src/components/forms/ItemQuantityForm.tsx
  src/components/forms/ShareListForm.tsx
  src/components/unauthenticated/UnauthenticatedNavBar.tsx
  src/declarations.d.ts
  src/index.tsx
  src/styles/_variables.scss
  src/styles/global.scss
  src/views/Layout.scss
  src/views/Layout.tsx
  src/views/authenticated/List.tsx
  src/views/unauthenticated/About.tsx
  src/views/unauthenticated/UnauthenticatedHome.scss
  src/views/unauthenticated/UnauthenticatedHome.tsx
Labels: enhancement, design

#68 my testing of fixes to fix the mobile issue
  src/components/ListItem.tsx
  src/components/NavBar.scss
  src/components/forms/ItemQuantityForm.tsx
  src/styles/global.scss
  src/views/authenticated/List.tsx
Labels: bug fix

#67 Issue # 56. Designing responsive list component for the list page
  package-lock.json
  package.json
  src/components/FilterListInput.tsx
  src/components/ListItem.scss
  src/components/ListItem.tsx
  src/components/NavBar.scss
  src/components/authenticated/AuthenticatedNavBar.tsx
  src/components/forms/AddItemForm.scss
  src/components/forms/AddItemForm.tsx
  src/components/forms/ItemQuantityForm.tsx
  src/components/forms/ShareListForm.scss
  src/components/forms/ShareListForm.tsx
  src/styles/global.scss
  src/views/Layout.scss
  src/views/authenticated/List.scss
  src/views/authenticated/List.tsx
  src/views/authenticated/ManageList.tsx
Labels: design
